// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bofcuqcjujbcviiealzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvZmN1cWNqdWpiY3ZpaWVhbHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDA5ODAsImV4cCI6MjA3MzE3Njk4MH0.ebmZvfg6x7s8CHbBSgg5iRGYGQhdVJR4mLNVuwGSXe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});